apiVersion: v1
kind: Service
metadata:
  name: insurance-app-service
  namespace: insurance-application
  labels:
    app: insurance-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  selector:
    app: insurance-app
